version: "3"
services:

  objectstorage:
    image: minio/minio:RELEASE.2018-09-25T21-34-43Z
    volumes:
      - ./data/objectstorage:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: exodusexodus
      MINIO_SECRET_KEY: exodusexodus
    command: ["minio", "server", "/data"]

  db:
    image: postgres:9.6
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: exodus
      POSTGRES_PASSWORD: exodus
      POSTGRES_DB: exodus
      PGDATA: /var/lib/postgresql/data/pgdata

  amqp:
    image: rabbitmq:3.7-alpine
    ports:
      - "5672:5672"
