- name: download minio
  get_url:
    url: https://dl.minio.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2018-06-09T03-43-35Z
    checksum: sha256:4f04502b496b4ef16727673eec191e0993986251c2b2b5adc7f1ee5bfbe3a93d
    dest: ~/minio
    mode: u+x

- name: create configuration directory
  file:
    path: ~/.minio
    state: directory

- name: copy configuration
  copy:
    src: config.json
    dest: ~/.minio/

- name: create minio storage location
  file:
    path: /vagrant/storage
    state: directory

- name: copy minio service
  become: true
  copy:
    src: minio.service
    dest: /etc/systemd/system

- name: start minio service
  become: true
  systemd:
    name: minio
    state: started
    daemon_reload: yes
    enabled: yes
