- name: install psycopg2
  become: true
  apt:
    name: python-psycopg2
    state: present

- name: Install postgresql
  become: true
  apt:
    name: postgresql-9.6
    state: present

- name: Start prostgresql service
  become: true
  service:
    name: postgresql
    state: started
    enabled: true

- name: create database
  become: true
  become_user: postgres
  postgresql_db:
    name: exodus

- name: create user
  become: true
  become_user: postgres
  postgresql_user:
    name: exodus
    password: exodus
    db: exodus
